#!/bin/bash

dotfiles=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
for dotfile in $(find "$dotfiles" -maxdepth 1 -name ".*" ! -name '.git')
do
    file=$(basename $dotfile)
    if [[ -f $HOME/$file || -d $HOME/$file ]]
    then
	if [ -L $HOME/$file ]
	then
	    echo "link already exists - $HOME/$file > $(readlink $HOME/$file)"

	else
	    echo "file already exists - $dotfile"
	fi
	continue
    fi
    echo "linking $HOME/$file to $dotfile"
    ln -s $dotfile $HOME/$file
done
